version: "3.8"

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "10001:10001"
    networks:
      - internal
    depends_on:
      - mongodb
    env_file:
      - .env

  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    ports:
      - "10002:10002"
    networks:
      - internal
    depends_on:
      - mongodb
    env_file:
      - .env

  swiss-bank-user-interface:
    build:
      context: ./swiss-bank-user-interface
      dockerfile: Dockerfile
    networks:
      - internal
    depends_on:
      - user-service
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - internal

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - swiss-bank-user-interface
      - user-service
    networks:
      - internal
      - external

networks:
  internal:
    driver: bridge
  external:
    driver: bridge

volumes:
  mongo-data:
