version: "3.8"

services:
  swiss-bank-common:
    build:
      context: .
      dockerfile: swiss-bank-common.Dockerfile
    depends_on:
      - mongodb
    env_file:
      - .env

  user-service:
    build:
      context: .
      dockerfile: user-service.Dockerfile
    ports:
      - "10001:10001"
    networks:
      - internal
    depends_on:
      - mongodb
      - swiss-bank-common
    env_file:
      - .env

  account-service:
    build:
      context: .
      dockerfile: account-service.Dockerfile
    ports:
      - "10002:10002"
    networks:
      - internal
    depends_on:
      - mongodb
      - swiss-bank-common
    env_file:
      - .env

  payment-service:
    build:
      context: .
      dockerfile: payment-service.Dockerfile
    ports:
      - "10009:10009"
    networks:
      - internal
    depends_on:
      - mongodb
      - swiss-bank-common
    env_file:
      - .env
    environment:
      JDK_JAVA_OPTIONS: --add-opens java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED

  swiss-bank-user-interface:
    build:
      context: ./swiss-bank-user-interface
      dockerfile: Dockerfile
    networks:
      - internal
    depends_on:
      - user-service
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - internal

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - swiss-bank-user-interface
      - user-service
    networks:
      - internal
      - external

networks:
  internal:
    driver: bridge
  external:
    driver: bridge

volumes:
  mongo-data:
